spring:
  application:
    name: jiang-ddns
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
