debug: true
jiang:
  ip-obtaining:
    strategy: http-string
    http-string:
      url: http://www.bing.com
server:
  port: 40040
spring:
  application:
    name: jiang-ddns
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: jcache
    jcache:
      config: ehcache.xml
logging:
  level:
    org.springframework.boot.autoconfigure: error
