debug: true
jiang:
  ip-obtaining:
    strategy: http-string
    http-string:
      url: http://members.3322.org/dyndns/getip
      connect-timeout: 5s
  ip-flushing:
    strategy: aliyun
    aliyun:
      access-key-id:
      access-key-secret:
      condition:
        domain-name:
        remark-regex:
  dynamic-flush-dns:
    cron: 0 */3 * * * *
server:
  port: 40040
spring:
  application:
    name: jiang-ddns
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
logging:
  level:
    org.springframework.boot.autoconfigure: error
